[package]
name = "simpledb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

build = "capnp/build.rs"

[build-dependencies]
capnpc = "0.14.7"

[dependencies]
anyhow = "1.0.58"
capnp = "0.14.6"
capnp-rpc = "0.14.1"
chrono = "0.4.19"
combine = "4.6.4"
env_logger = "0.9.0"
futures = "0.3.21"
itertools = "0.10.3"
log = "0.4.17"
num-derive = "0.3.3"
num-traits = "0.2.15"
rand = "0.8.5"
structopt = "0.3.26"
tokio = {version = "1.19.2", features = ["full"]}
tokio-util = {version = "0.7.3", features = ["compat"]}

[lib]
name = "simpledb"
path = "src/lib.rs"

[[bin]]
name = "esql"
path = "app/embedded/main.rs"

[[bin]]
name = "simpledb-server"
path = "app/network/server.rs"

[[bin]]
name = "sql"
path = "app/network/client.rs"