[package]
name = "simpledb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.52"
combine = "4.6.3"
either = "1.6.1"
getopts = "0.2"
itertools = "0.10.3"
num-derive = "0.3"
num-traits = "0.2"
rand = "0.8.5"

tarpc = {version = "0.27", features = ["tokio1", "serde-transport", "serde1", "tcp"]}
tokio = {version = "1.17", features = ["rt", "macros", "rt-multi-thread"]}
tokio-util = {version = "0.7", features = ["compat"]}
tokio-serde = {version = "0.8", features = ["bincode"]}
futures = "0.3"
interprocess = {version = "1.1", features = ["nonblocking"]}
serde = {version = "1.0", features = ["rc"]}

[lib]
name = "simpledb"
path = "src/lib.rs"

[[bin]]
name = "esql"
path = "src/esql.rs"
