[package]
name = "simpledb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
combine = "4.6.3"
either = "1.6.1"
env_logger = "0.9"
getopts = "0.2"
itertools = "0.10.3"
log = "0.4"
num-derive = "0.3"
num-traits = "0.2"
rand = "0.8.5"

[lib]
name = "simpledb"
path = "src/lib.rs"

[[bin]]
name = "esql"
path = "app/esql.rs"
